version: "3.5"

############################################################
##
## NETWORK
##
############################################################

#-----------------------------------------------------------
# Ex: Create new network
#-----------------------------------------------------------
networks:
  grph_net:
    name: grph_net

#-----------------------------------------------------------
# Ex: Reuse network from another docker-compose
#-----------------------------------------------------------
#networks:
#  grph_net:
#    external:
#      name: grph_net


############################################################
##
## CONFIG
##
############################################################


x-production-options:
  &production_opts
  restart: unless-stopped
  networks:
    - grph_net
  env_file:
    - ../envs/general.env
    - ../envs/graphistry.env
    - ./.env

x-build-kwargs:
  &build_kwargs
  args:
    - DOCKER_TAG=${DOCKER_TAG:-latest}
    - BUILDKIT_INLINE_CACHE=1    


############################################################
##
## SERVICES
##
############################################################

services:
  streamlit:
    << : *production_opts
    image: graphistry/graph-app-kit-st:${DOCKER_TAG:-latest}
    command: --server.baseUrlPath="$BASE_PATH" /apps/entrypoint.py
    build:
      << : *build_kwargs
      context: ..
      dockerfile: ./docker/Dockerfile
      cache_from:
        - graphistry/graph-app-kit-st:${DOCKER_TAG:-latest}
    container_name: "streamlit"
    ports:
      - "8501:8501"
    volumes:
      - ../python:/apps
    healthcheck:
      test: ["CMD", "curl", "-Lf", "http://localhost:8501/$BASE_PATH/healthz"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 10s
